name: nest rest cqrs example

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          auto_fix: true
          commit_message: "style: code style issues with ${linter}"
          eslint_extensions: ts
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm test

  build-image:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --driver docker-container --use
        docker buildx build --platform linux/amd64,linux/arm64 -t kyhsa93/nestjs-rest-cqrs-example:${{ github.sha }} --push .
